name: 'ytmusic_analytics'
version: '1.0.0'
profile: 'user'

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ytmusic_analytics:
    +schema: dbt_laltazin

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: view
