version: 2

models:
  - name: stg_ytmusic
    columns:
      - name: track_id
        tests: [not_null]

  - name: stg_spotify
    columns:
      - name: spotify_track_id
        tests: [not_null]
